### DISCUSSION TITLE
appimage build with linuxdeploy no longer crash with (CTRL + O)

### DISCUSSION THREAD

**Discussion by GerryFerdinandus** [collin80/SavvyCAN#849] [General]
Tested on Manjaro rolling release Linux

The current appimage dev + release crashes when menu => open file is selected.

Rebuilding the program with **linuxdeploy** instead of **linuxdeployqt** gives a better result. It no longer crashes when  (CTRL + O) 

GitHub action Appimage built from 3 different Ubuntu server all works. 
```

name: Build

on:
  push:
    branches:
      - "master"
      
jobs:
  buildlinux:
    name: Linux x64
    runs-on: ${{ matrix.os }}

    strategy:
      # Set up an array to perform the following three build configurations.
      matrix:
        os: [ubuntu-20.04, Ubuntu-22.04, ubuntu-24.04]
        include:
          - os: ubuntu-20.04
            RELEASE_FILE_NAME: SavvyCAN-Ubuntu_20.04_x86_64.AppImage
          - os: ubuntu-22.04
            RELEASE_FILE_NAME: SavvyCAN-Ubuntu_22.04_x86_64.AppImage
          - os: ubuntu-24.04
            RELEASE_FILE_NAME: SavvyCAN-Ubuntu_24.04_x86_64.AppImage

    steps:
      # need 'fuse' for ubuntu 22.04 and 24.04
      - name: Prepare Environment
        run: |
            sudo apt-get install fuse libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-render-util0 libxcb-xinerama0 libxcb-randr0 libxkbcommon-x11-0

      - name: Prepare Qt Libraries
        uses: jurplel/install-qt-action@v4
        with:
          version: '5.15.*'

      - name: Clone
        uses: actions/checkout@v4

      - name: Compile and install
        run: |
          qmake CONFIG+=release PREFIX=/usr SavvyCAN.pro
          make -j`grep -c ^processor /proc/cpuinfo`
          make INSTALL_ROOT=appdir install

      - name: Download linuxdeploy
        run:  |
          curl -L -O  https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-static-x86_64.AppImage
          curl -L -O  https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-static-x86_64.AppImage
          curl -L -O  https://github.com/linuxdeploy/linuxdeploy-plugin-appimage/releases/download/continuous/linuxdeploy-plugin-appimage-x86_64.AppImage
          chmod +x linuxdeploy-*.AppImage
        shell: bash

      - name: Create AppImage
        env:
          LDAI_NO_APPSTREAM: 1
          LDAI_OUTPUT: ${{ matrix.RELEASE_FILE_NAME }}
        run:  |
          ./linuxdeploy-static-x86_64.AppImage \
            --output appimage \
            --appdir appdir \
            --plugin qt \
            --icon-file appdir/usr/share/icons/icons/hicolor/256x256/apps/SavvyCAN.png \
            --desktop-file appdir/usr/share/applications/SavvyCAN.desktop \
            --executable appdir/usr/bin/SavvyCAN 
        shell: bash

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.RELEASE_FILE_NAME }}
          path: ${{ matrix.RELEASE_FILE_NAME }}
          compression-level: 0 # no compression. Content is already a compress file
          if-no-files-found: error

```

### linuxdeploy appimage version warning in terminal is only one line + working (CTRL + O) 
`
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
`

With **linuxdeployqt** build I get warnings about missing GTK items etc. And then crashes when (CTRL + O)
